name: null
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.53509
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cae4cb'
    - '#81bab3'
    - '#1f6072'
    - '#900000'
    - '#0b2325'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose:
  - name: engagement
    item: 47d5f72c-d42a-43c3-b3d7-58bf7f88b66f
    url: null
