name: Movies
favicon: null
layout_spectrum: 0.24694
typography_spectrum: 0.59271
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4e5d7a'
    - '#303539'
    - '#100c0d'
    - '#828e9e'
    - '#d5d3d4'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose:
  - name: engagement
    item: d09245a5-79b1-4ab3-8e07-d056baf8b36d
    url: null
