name: Movies
favicon: null
layout_spectrum: 0.68019
typography_spectrum: 0.19934
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cae4cb'
    - '#81bab3'
    - '#1f6072'
    - '#900000'
    - '#0b2325'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.25
purpose:
  - name: engagement
    item: d09245a5-79b1-4ab3-8e07-d056baf8b36d
    url: null
